[project]
name = "ReSyncSuvey"
version = "0.9"
description = "Reprojecting Survey Synchronisation Script"
authors = ["Lindsay Bradford <lindsay.bradford@truii.com>"]

[project.dependencies]
pytest = "8.2.1"

[tool.pytest.ini_options]
pythonpath = "."
addopts = [
    "--import-mode=importlib",
]