[project]
name = "ReprojectSuvey"
version = "0.0.1"
description = "Reproject Survey Utility Script"
authors = ["Lindsay Bradford <lindsay.bradford@truii.com>"]

[project.dependencies]
pytest = "8.2.1"

[tool.pytest.ini_options]
pythonpath = "."
addopts = [
    "--import-mode=importlib",
]